# Generated by Django 3.0.5 on 2022-05-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='APPLIED_SERIAL_NOS',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='DATE_CODE',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='LAYER_COUNT',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='MANUFACTURER_NAME',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='PANEL_NO',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='PCB_SI_NOS',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='PCB_THICKNESS',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='PROJECT',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Result_day',
        ),
    ]
