# Generated by Django 3.0.5 on 2022-06-01 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220601_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='PANEL_NO',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
