# Generated by Django 3.0.5 on 2022-06-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_panel_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Microsection',
        ),
    ]
