# Generated by Django 3.0.5 on 2022-06-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_microsection_manufacturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsection',
            old_name='MANUFACTURER_NAME',
            new_name='DATE_CODE',
        ),
        migrations.RemoveField(
            model_name='microsection',
            name='PANEL_NO',
        ),
    ]
