# Generated by Django 3.0.5 on 2022-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220601_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='MANUFACTURER_NAME',
            field=models.CharField(default='SELECT A MANUFACTURER', max_length=122),
            preserve_default=False,
        ),
    ]
