# Generated by Django 3.0.5 on 2022-06-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_microsection_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='PANEL_NO',
            field=models.CharField(default='Enter panel number', max_length=122),
            preserve_default=False,
        ),
    ]
