# Generated by Django 3.0.5 on 2022-06-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_microsection_panel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='APPLIED_SERIAL_NOS',
            field=models.CharField(default='Emnter serial number', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='LAYER_COUNT',
            field=models.CharField(default='Enter layer count', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='PCB_SI_NOS',
            field=models.CharField(default='Enter PCN SI number', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='PCB_THICKNESS',
            field=models.CharField(default='Enter PCB thickness', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='PROJECT',
            field=models.CharField(default='Enter project', max_length=122),
            preserve_default=False,
        ),
    ]
