# Generated by Django 3.0.5 on 2022-06-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220601_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='TESTING_AGENCY',
            field=models.CharField(default='Enter testing agency', max_length=122),
            preserve_default=False,
        ),
    ]
