# Generated by Django 3.0.5 on 2022-06-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_microsection_testing_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='Load_Month',
            field=models.CharField(default='Enter month', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Load_Year',
            field=models.CharField(default='Enter year', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Load_day',
            field=models.CharField(default='Enter Day', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Receipt_Day',
            field=models.CharField(default='Enter Day', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Receipt_Month',
            field=models.CharField(default='Enter Month', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Receipt_Year',
            field=models.CharField(default='Enter Year', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Result_Month',
            field=models.CharField(default='Enter Month', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Result_Year',
            field=models.CharField(default='Enter Year', max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsection',
            name='Result_day',
            field=models.CharField(default='Enter day', max_length=122),
            preserve_default=False,
        ),
    ]
