# Generated by Django 3.0.5 on 2022-06-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_microsection_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsection',
            name='REMARKS',
            field=models.CharField(default='Enter remarks', max_length=122),
            preserve_default=False,
        ),
    ]
