# Generated by Django 3.0.5 on 2022-06-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_microsection_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsection',
            old_name='REMARKS',
            new_name='REMARK',
        ),
    ]
