# Generated by Django 3.0.5 on 2022-06-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220601_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsection',
            name='REMARK',
        ),
    ]
